{% set name = "dftd4" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 60d4f30d97cae95a7b48a99e10848ef600b605f9da98c4893a6034bded1a7f24

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - asciidoctor
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib
  run:
    - mctc-lib

test:
  commands:
    - dftd4 --version

about:
  home: https://github.com/dftd4/dftd4
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A generally applicable London dispersion correction
  description: |
    This program implements the D4 London dispersion correction
    for molecular and 3D periodic systems.
  doc_url: https://dftd4.github.io/dftd4

extra:
  recipe-maintainers:
    - awvwgk
