{% set name = "dftd4" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f3b0a16a952817ae48e819626e13676fba3b61c8beea47b0f8ada2fbb679fb7b
  patches:
    - wrap.patch
    - gcc5.patch  # [win]

build:
  number: 0
  script:
    - set -ex  # [unix]
    - mv $PREFIX/lib/pkgconfig/{lapack,blas}.pc $SRC_DIR  # [unix]
    - meson setup _build ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib} --buildtype=release -Dlapack=custom -Dcustom_libraries=lapack,blas  # [unix]
    - meson setup _build --prefix=%PREFIX% --buildtype=release --pkg-config-path=%PREFIX%\lib\pkgconfig -Dlapack=custom "-Dfortran_link_args=%LIBRARY_PREFIX%\lib\liblapack.dll.a %LIBRARY_PREFIX%\lib\libblas.dll.a"  # [win]
    - meson compile -C _build
    - meson test -C _build --no-rebuild --print-errorlogs  # [build_platform == target_platform]
    - meson install -C _build --no-rebuild
    - mv $SRC_DIR/{lapack,blas}.pc $PREFIX/lib/pkgconfig  # [unix]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - cmake  # [win]
    - asciidoctor  # [unix]
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib
  run:
    - mctc-lib

test:
  requires:
    - pkg-config
  commands:
    - {{ name }} --version  # [build_platform == target_platform]
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - set PKG_CONFIG_PATH=%PREFIX%\lib\pkgconfig  # [win]
    - pkg-config {{ name }} --exact-version {{ version }}

about:
  home: https://github.com/dftd4/dftd4
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A generally applicable London dispersion correction
  description: |
    This program implements the D4 London dispersion correction
    for molecular and 3D periodic systems.
  doc_url: https://dftd4.github.io/dftd4

extra:
  recipe-maintainers:
    - awvwgk
