{% set name = "dftd4" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/797a8c6fc5f5ed4d5a558694966dd3fa31028161.tar.gz
  sha256: 246cb2c39ad011afaf198f8e7eb44195a3f484066721c9c8ea91421a54318ee3

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - meson 0.55.*
    - ninja
    - asciidoctor
  host:
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - libblas
    - liblapack

test:
  commands:
    - dftd4 --version

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'A generally applicable London dispersion correction'
  description: |
    This program implements the D4 London dispersion correction
    for molecular and 3D periodic systems.

extra:
  recipe-maintainers:
    - awvwgk
