{% set name = "dftd4" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/releases/download/v{{ version }}/dftd4-{{ version }}-source.tar.xz
  sha256: ed4a6a3ba0a89b8d6825bf11724dee647fd8ee6272e7822e0cbd9847994eb872

build:
  number: 0

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - cmake  # [win]
    - asciidoctor  # [unix]
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib
    - multicharge
    - pkg-config

test:
  requires:
    - pkg-config
  commands:
    - {{ name }} --version  # [build_platform == target_platform]
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - test -f $PREFIX/include/{{ name }}.h  # [unix]
    - pkg-config {{ name }} --exact-version {{ version }}
    - if not exist %LIBRARY_BIN%\\lib{{ name }}-4.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\{{ name }}.h exit 1  # [win]

about:
  home: https://github.com/dftd4/dftd4
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A generally applicable London dispersion correction
  description: |
    This program implements the D4 London dispersion correction
    for molecular and 3D periodic systems.
  doc_url: https://dftd4.readthedocs.io

extra:
  recipe-maintainers:
    - awvwgk
    - marvinfriede
