{% set name = "dftd4" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 014e2917f2b636c062325d59a4a0f068550bd3b119742be80e956456478ee2d6
  patches:
    - dftd4-build.patch
    - dftd4-openmp-gcc7.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - meson >=0.49
    - ninja
  host:
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - libblas
    - liblapack

test:
  commands:
    - dftd4 --version

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'A generally applicable London dispersion correction'
  description: |
    This program implements the D4 London dispersion correction
    for molecular and 3D periodic systems.

extra:
  recipe-maintainers:
    - awvwgk
