conda_forge_output_validation: true
test_on_native_only: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux_ppc64le: default
  linux_aarch64: default
